app = "demo-samvad"
primary_region = "sin"

[build]

[env]
  PORT = "3003"
  DEMO_URL = "https://demo-samvad.fly.dev"

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
